[workspace]
members = ["extensions/*", "common/*"]
exclude = [
    "extensions/manhuafast",
    "extensions/nhentai",
    "extensions/reaperscans",
    "extensions/365manga",
    "extensions/firstkissmanhua",
]