[workspace]
members = ["extensions/*", "common/*"]
exclude = [
    "extensions/manhuafast",
    "extensions/nhentai",
    "extensions/reaperscans",
    "extensions/365manga",
    "extensions/firstkissmanhua",
    "extensions/mmscans",
]

[profile.release]
strip = true
opt-level = "z"
lto = true
