[workspace]
members = ["extensions/*", "common/*"]
exclude = [
    "extensions/firstkissmanhua",
    "extensions/isekaiscan",
    "extensions/nhentai",
    "extensions/reaperscans",
    "extensions/365manga",
]