[package]
name = "three_sixty_five_manga"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tanoshi-lib = "0.27.0"
madara = { path = "../../common/madara" }
anyhow = "1"
