[package]
name = "guya"
version = "0.2.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
networking = { path = "../../common/networking" }
tanoshi-lib = "0.27.0"
guyalib = { path = "../../common/guyalib" }
anyhow = "1"
lazy_static = "1"
