[package]
name = "wpmangareader"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
networking = { path = "../networking" }
tanoshi-lib = "0.27.0"
chrono = "0.4"
scraper = "0.13"
anyhow = "1"
