[package]
name = "manganato"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
networking = { path = "../../common/networking" }
tanoshi-lib = "0.27.0"
mangakakalot-common = { path = "../../common/mangakakalot" }
anyhow = "1"
lazy_static = "1"
