name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .gitignore
      - "**/*.md"

env:
  RUST_TOOLCHAIN: 1.79.0

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            arch: x86_64
            target: x86_64-unknown-linux-gnu
            extension: so          
          - os: ubuntu-latest
            arch: aarch64
            target: aarch64-unknown-linux-gnu
            extension: so
          - os: macos-latest
            arch: x86_64
            target: x86_64-apple-darwin
            extension: dylib
          - os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc
            extension: dll
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: houseabsolute/actions-rust-cross@v0
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: ${{ matrix.platform.target }} 
          command: build
          args: "--release"
      
      - name: Generate json
        if: ${{ matrix.platform.target == 'x86_64-unknown-linux-gnu' }}
        run: |
          URL=$(curl -sL "https://api.github.com/repos/luigi311/tanoshi/releases/latest" | grep "tanoshi-cli" | grep '"browser_download_url":' | sed -E 's/.*"([^"]+)".*/\1/') 
          curl -L $URL -o $HOME/.cargo/bin/tanoshi-cli
          chmod +x $HOME/.cargo/bin/tanoshi-cli
          $HOME/.cargo/bin/tanoshi-cli --path target/${{ matrix.platform.target }}/release generate-json
          mv output/${{ matrix.platform.target }}/index.json output/

      - if: ${{ matrix.platform.target != 'x86_64-unknown-linux-gnu' }}
        run: |
          mkdir -p output/${{ matrix.platform.target }}/
          cp target/${{ matrix.platform.target }}/release/*.${{ matrix.platform.extension }} output/${{ matrix.platform.target }}/
      
      - if: ${{ matrix.platform.target != 'x86_64-unknown-linux-gnu' && matrix.platform.target != 'x86_64-pc-windows-msvc' }}
        run: cd output/${{ matrix.platform.target }}/ && for f in *.${{ matrix.platform.extension }};do mv $f ${f#lib}; done; cd ../..
      
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: repo-${{ env.RUST_TOOLCHAIN }}
          path: output
  
  push:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - name: Clone repo
        run: |
          git clone https://github.com/luigi311/tanoshi-extensions repository
          cd repository
          # Create branch if not exists
          git checkout ${{ env.RUST_TOOLCHAIN }} || git checkout -b ${{ env.RUST_TOOLCHAIN }}
          # Remove all existing files
          rm -rf *
          cd ..
          
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: repo-${{ env.RUST_TOOLCHAIN }}
          path: repository

      - name: Commit files
        run: |
          cd repository
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "deploy"
          cd ..

      - name: Git Commit and Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RUST_TOOLCHAIN }}
          directory: repository
